/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData adjust = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData airport_shuttle = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData arrow_back = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData qr_code = const IconData(0xe803, fontFamily: _kFontFam);
}
